[workspace]
name = "powerline"
version = "0.1.0"
description = "Environment for powerline image annotation"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
python = ">=3.14.2,<3.15"

[tasks]

[pypi-dependencies]
ultralytics = ">=8.3.235, <9"
polars = { version = ">=1.36.1, <2", extras = ["rtcompat"] }
pandas = ">=2.0.0, <3"
